version: '4.0'

services: 
 postgres: 
  image: postgres:13
    enviroment: 
      POSTGRES_USER: admin@admin.com
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_db
  ports: 
    - "5432:5432" 
  volumenes: 
    - ./data/postgress:/var/lib/